export const JOB_DATA = {
  osi: {
    title: 'Software Developer',
    company: 'OSI Systems',
    url: 'https://screeningsolution.com/certscan-platform',
    dates: 'Jan 2021 - Jul 2022',
    points: [
      'Collaborated with a 15-member team to develop and implement RESTful Microservices for CertScan’s backend using Java, Spring Boot, Maven, Hibernate, and PostgreSQL, enhancing performance and reliability',
      'Designed and implemented live widgets on the CertScan dashboard using Angular, improving operational efficiency by 30%',
      'Developed a CI/CD pipeline with Jenkins, Docker, Kubernetes, AWS, and Ansible, ensuring consistent and rapid environment provisioning, increasing deployment reliability by 20%',
    ],
  },
  uf: {
    title: 'Graduate Student Assistant',
    company: 'University of Florida',
    url: 'https://www.ufl.edu/',
    dates: 'Dec 2022 - May 2024',
    points: [
      'Collaborated with Dr. Sartaj Sahni for the course “Advanced Data Structures,” holding office hours, evaluating assignments, and exams. Provided comprehensive feedback to a diverse class of over 330 students.',
      'Developed a React-Node-Express-Mongo website, enhancing NLP annotation. Increased researcher productivity by over 50%, revolutionizing data annotation efficiency in NLP.',
    ],
  },
  drdl: {
    title: 'Research Intern',
    company: ' Defense Research & Development Laboratory (DRDL)',
    url: '',
    dates: 'March 2021 - May 2021',
    points: [
      'Customized and implemented YOLOv3, a real-time object detection algorithm, to detect and classify various types of ships in the project "Sea targets detection and classification using YOLOv3".',
      'Achieved a mean average precision (mAP) of 98% @ IoU 0.5 with an inference time of 0.224 seconds on NVIDIA Tesla P4 GPU leveraging the capabilities of TensorFlow, NumPy, and OpenCV libraries for the implementation.',
    ],
  },
};
export const SKILLS_DATA = [
  'Java',
  'Python',
  'JavaScript',
  'SQL',
  'HTML',
  'CSS',
  'C#',
  'React',
  'Node',
  'Angular',
  'jQuery',
  'Bootstrap',
  'Tailwind',
  'Spring Boot',
  'Spring MVC',
  'Express',
  'REST',
  'Webpack',
  'PostgreSQL',
  'OracleDB',
  'MongoDB',
  'Jenkins',
  'Git',
  'Sourcetree',
  'Jira',
  'Postman',
  'Docker',
  'Kubernetes',
  'AWS',
];
